# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NdviSatveg
                                 A QGIS plugin
 Gera uma curva NDVI para a área de interesse
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-28
        copyright            : (C) 2025 by Eliandra Silva e Poliana Betella
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NdviSatveg class from file NdviSatveg.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .NDVI_DATVeg import NdviSatveg
    return NdviSatveg(iface)
